mariadb:
  image: mariadb
  environment:
  - MYSQL_DATABASE=racktables
  - MYSQL_USER=racktables
  - MYSQL_PASSWORD=password123
  - MYSQL_RANDOM_ROOT_PASSWORD=password123
  volumes:
  - ./db_data:/var/lib/mysql

racktables:
  image: xtha/racktables
  links:
  - mariadb
  environment:
  - DBHOST=mariadb
  - DBNAME=racktables
  - DBUSER=racktables
  - DBPASS=password123

nginx:
  image: nginx:stable-alpine
  links:
  - racktables
  volumes_from:
  - racktables
  volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf
  ports:
  - 8000:80
